# Generated by Django 3.0.7 on 2020-07-09 02:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='B118Basin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mantis_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('active_in_mantis', models.BooleanField(default=False)),
                ('geometry', models.TextField(blank=True, null=True)),
                ('b118_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mantis_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('active_in_mantis', models.BooleanField(default=False)),
                ('geometry', models.TextField(blank=True, null=True)),
                ('ab_code', models.CharField(max_length=4)),
                ('ansi_code', models.CharField(max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('caml_code', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CVHMFarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mantis_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('active_in_mantis', models.BooleanField(default=False)),
                ('geometry', models.TextField(blank=True, null=True)),
                ('farm_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MantisServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveSmallIntegerField(default=1234)),
                ('online', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubBasin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mantis_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('active_in_mantis', models.BooleanField(default=False)),
                ('geometry', models.TextField(blank=True, null=True)),
                ('subbasin_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('ready', models.BooleanField(default=False)),
                ('running', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('status_message', models.CharField(blank=True, default='', max_length=2048, null=True)),
                ('result_values', models.TextField(blank=True, default='', null=True, validators=[django.core.validators.int_list_validator])),
                ('date_submitted', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('b118_basin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_runs', to='npsat_manager.B118Basin')),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_runs', to='npsat_manager.County')),
                ('cvhm_farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_runs', to='npsat_manager.CVHMFarm')),
                ('subbasin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_runs', to='npsat_manager.SubBasin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CropGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=255)),
                ('crops', models.ManyToManyField(related_name='groups', to='npsat_manager.Crop')),
            ],
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proportion', models.DecimalField(decimal_places=4, max_digits=5)),
                ('land_area_proportion', models.DecimalField(decimal_places=4, max_digits=5)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='modifications', to='npsat_manager.Crop')),
                ('model_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='npsat_manager.ModelRun')),
            ],
            options={
                'unique_together': {('model_run', 'crop')},
            },
        ),
    ]
