# Generated by Django 3.0.7 on 2020-08-13 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('npsat_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelrun',
            old_name='region',
            new_name='regions',
        ),
    ]
