# Generated by Django 3.0.7 on 2020-07-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npsat_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrun',
            name='unsaturated_zone_travel_time',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=18),
            preserve_default=False,
        ),
    ]
