# Generated by Django 2.1.1 on 2019-01-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npsat_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='B118_Basin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npsat_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('b118_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npsat_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('fips_id', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
