# Generated by Django 2.1.1 on 2019-01-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npsat_manager', '0002_b118_basin_county'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='B118_Basin',
            new_name='B118Basin',
        ),
        migrations.RemoveField(
            model_name='county',
            name='fips_id',
        ),
        migrations.AddField(
            model_name='county',
            name='ab_code',
            field=models.CharField(default=None, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='county',
            name='ansi_code',
            field=models.CharField(default=None, max_length=3),
            preserve_default=False,
        ),
    ]
