# Generated by Django 3.0.7 on 2020-07-15 19:11

from django.db import migrations, models
import npsat_manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('npsat_manager', '0002_modelrun_unsaturated_zone_travel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b118basin',
            name='geometry',
            field=npsat_manager.models.SimpleJSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='county',
            name='geometry',
            field=npsat_manager.models.SimpleJSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cvhmfarm',
            name='geometry',
            field=npsat_manager.models.SimpleJSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelrun',
            name='unsaturated_zone_travel_time',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='subbasin',
            name='geometry',
            field=npsat_manager.models.SimpleJSONField(blank=True, null=True),
        ),
    ]
