# Generated by Django 3.0.7 on 2020-08-10 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('npsat_manager', '0003_auto_20200715_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultLoading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loading', models.FloatField()),
                ('year', models.SmallIntegerField()),
                ('well', models.IntegerField()),
                ('model_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='npsat_manager.ModelRun')),
            ],
        ),
    ]
