# Generated by Django 2.1.1 on 2019-01-26 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('npsat_manager', '0004_auto_20190123_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reduction', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='b118basin',
            name='active_in_npsat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='county',
            name='active_in_npsat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crop',
            name='caml_code',
            field=models.PositiveSmallIntegerField(default=606),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modification',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='modifications', to='npsat_manager.Crop'),
        ),
    ]
