# Generated by Django 2.1.1 on 2019-02-05 02:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('npsat_manager', '0005_auto_20190125_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_values', models.CharField(max_length=4096, validators=[django.core.validators.int_list_validator])),
                ('date_run', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='run_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
