# Generated by Django 2.1.1 on 2019-02-05 02:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('npsat_manager', '0006_runresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False)),
                ('status_message', models.CharField(max_length=2048)),
                ('result_values', models.CharField(max_length=4096, validators=[django.core.validators.int_list_validator])),
                ('date_run', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='run_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='runresult',
            name='user',
        ),
        migrations.DeleteModel(
            name='RunResult',
        ),
        migrations.AddField(
            model_name='modification',
            name='model_run',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='npsat_manager.ModelRun'),
            preserve_default=False,
        ),
    ]
