# Generated by Django 2.2.5 on 2019-11-11 21:44

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('npsat_manager', '0009_auto_20190409_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='MantisServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveSmallIntegerField(default=1234)),
                ('online', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='modelrun',
            name='running',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='modelrun',
            name='date_run',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 21, 44, 53, 723581, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='modelrun',
            name='result_values',
            field=models.CharField(default='', max_length=4096, null=True, validators=[django.core.validators.int_list_validator]),
        ),
        migrations.AlterField(
            model_name='modelrun',
            name='status_message',
            field=models.CharField(default='', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='modification',
            name='model_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modifications', to='npsat_manager.ModelRun'),
        ),
    ]
