# Generated by Django 2.2.5 on 2019-11-12 18:18

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('npsat_manager', '0012_auto_20191111_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelrun',
            name='date_run',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 12, 18, 18, 41, 983707, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='modelrun',
            name='result_values',
            field=models.CharField(blank=True, default='', max_length=4096, null=True, validators=[django.core.validators.int_list_validator]),
        ),
        migrations.AlterField(
            model_name='modelrun',
            name='status_message',
            field=models.CharField(blank=True, default='', max_length=2048, null=True),
        ),
    ]
