# Generated by Django 2.2.5 on 2019-11-12 18:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('npsat_manager', '0013_auto_20191112_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelrun',
            name='date_run',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 12, 18, 22, 12, 75160, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='modification',
            name='model_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='npsat_manager.ModelRun'),
        ),
    ]
