# Generated by Django 2.2.5 on 2019-11-12 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('npsat_manager', '0015_auto_20191112_1022'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modification',
            unique_together={('model_run', 'crop')},
        ),
    ]
