# Generated by Django 3.0 on 2019-12-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npsat_manager', '0016_auto_20191112_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelrun',
            old_name='date_run',
            new_name='date_submitted',
        ),
        migrations.AddField(
            model_name='modelrun',
            name='date_completed',
            field=models.DateTimeField(null=True),
        ),
    ]
