# Generated by Django 3.0 on 2019-12-05 22:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('npsat_manager', '0017_auto_20191205_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelrun',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelrun',
            name='date_submitted',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
