# Generated by Django 3.0 on 2019-12-05 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('npsat_manager', '0018_auto_20191205_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrun',
            name='b118_basin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_runs', to='npsat_manager.B118Basin'),
        ),
        migrations.AddField(
            model_name='modelrun',
            name='cvhm_farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_runs', to='npsat_manager.CVHMFarm'),
        ),
        migrations.AddField(
            model_name='modelrun',
            name='subbasin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_runs', to='npsat_manager.SubBasin'),
        ),
    ]
