# Generated by Django 3.0 on 2019-12-13 00:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npsat_manager', '0019_auto_20191205_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelrun',
            name='result_values',
            field=models.TextField(blank=True, default='', null=True, validators=[django.core.validators.int_list_validator]),
        ),
    ]
