# Generated by Django 3.0.7 on 2020-07-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npsat_manager', '0020_auto_20191212_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrun',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelrun',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
