# Generated by Django 3.0.7 on 2020-07-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npsat_manager', '0021_auto_20200701_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='modification',
            name='land_area_proportion',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modification',
            name='proportion',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
    ]
